# Generated by Django 4.2.6 on 2023-10-26 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=80)),
                ('tel', models.CharField(max_length=15)),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_embauche', models.DateField()),
                ('matiere', models.CharField(max_length=70)),
                ('niveau', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=80)),
                ('tel', models.CharField(max_length=15)),
                ('post', models.CharField(max_length=20)),
                ('centre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=40)),
                ('centre', models.CharField(max_length=20)),
                ('professors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RsApp.professeur')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='groupe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RsApp.groupe'),
            preserve_default=False,
        ),
    ]
